
-- ============================================================
-- AI/ML CAREER TRACKER - SUPABASE DATABASE
-- Run this entire script once in Supabase SQL Editor.
-- ============================================================

create table if not exists public.tasks (
    task_id bigint primary key,
    day integer,
    week integer,
    month integer,
    subject text,
    topic text,
    subtopic text,
    what_to_learn text,
    study_time text,
    practice_time text,
    practice_task text,
    interview_time text,
    interview_question text,
    english_time text,
    english_practice text,
    project_work text,
    completed boolean default false
);

create table if not exists public.interview_questions (
    id bigint primary key,
    category text,
    question text,
    difficulty text,
    status text default 'Not Practiced'
);

create table if not exists public.english_practice (
    day integer primary key,
    completed boolean default false
);

create table if not exists public.job_applications (
    id bigint generated by default as identity primary key,
    company text,
    role text,
    source text,
    location text,
    status text,
    notes text,
    applied_date text
);

-- The Streamlit app uses the Supabase server-side key.
-- Keep SUPABASE_KEY private in Streamlit Secrets.
-- Do NOT put it in GitHub.

create index if not exists tasks_day_idx
on public.tasks(day);

create index if not exists tasks_month_idx
on public.tasks(month);

create index if not exists tasks_subject_idx
on public.tasks(subject);

create index if not exists interview_category_idx
on public.interview_questions(category);
